// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgedidtpqfashojqagbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnZWRpZHRwcWZhc2hvanFhZ2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDcyNDksImV4cCI6MjA3NDQyMzI0OX0.S-xJ6DarxU5Q-pl2jJfJmLvv5uKGQHa3CqfejXGO-gA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});